from docx import Document
from docx.shared import Inches
import pyttsx3

engine = pyttsx3.init()
def speak_slow(speed_rate):
    rate = engine.getProperty('rate')
    engine.setProperty('rate', rate-speed_rate)
    engine.runAndWait()
speak_slow(80)

def speak(text):
    pyttsx3.speak(text)


document = Document()

# profile picture
document.add_picture('shaju.png', width=Inches(1))

# name phone number and email
name = input('what is your name?')
speak('hello' + name + 'how are you today?')
speak('what is your phone number')
phone_number = input('what is your phone number?')
email = input('what is your email? ')
document.add_paragraph(name + ' | ' + phone_number + ' | ' + email )

# about me
document.add_heading('About Me')
about_me = input('Tell about yourself: ')
document.add_paragraph(about_me)

# work experiences
document.add_heading('Work Experience')
company = input('Company name: ')
from_date = input('From date: ')
to_date = input('To date: ')

p = document.add_paragraph()
p.add_run(company + ' ').bold = True
p.add_run(from_date + ' - ' + to_date + '\n').italic = True
work_experience = input('Describe work experience at ' + company + ' ')
p.add_run(work_experience)

while True:
    has_more_experiences = input('Do you have more experiences? Yes or No ')
    if has_more_experiences.lower() == 'yes':
        company = input('Company name: ')
        from_date = input('From date: ')
        to_date = input('To date: ')

        p = document.add_paragraph()
        p.add_run(company + ' ').bold = True
        p.add_run(from_date + ' - ' + to_date + '\n').italic = True
        work_experience = input('Describe work experience at ' + company + ' ')
        p.add_run(work_experience)
    else:
        break
# skills
document.add_heading('Skills')
skills = input('Enter your skills: ')
p = document.add_paragraph(skills)
p.style = 'List Bullet'

while True:
    more_skills = input('Do you have more skills: yes or no ')
    if more_skills.lower() == 'yes':
        skills = input('Enter your skills: ')
        p = document.add_paragraph(skills)
        p.style = 'List Bullet'
    else:
        break

# footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = 'cv generated by shaju'


document.save('cv.docx')
